### ISSUE TITLE
Create Developer Documentation

### ISSUE THREAD

**Issue by jhoshiko** [NREL/mappymatch#10]
Create developer documentation. Some sections we could include: 

- Get started or quick start guide 

- a variety of examples/use cases ranging from simple to complex

- API documentation

- matcher documentation

**Comment by Rowlando13** [comment]
I think we should close this and split this issue into the following issues: 

1. Getting started or quick start - possibly not open if it is good enough for now.
2. General review of documentation structure - should be done in a multiple PRs so as to not block people / generate a lot of conflicts. 
3. Developer documentation 
    - Developer specific install 
    - Workflow for contribution  
    - others TBD
4. API documentation - possibly not open if it is good enough for now. 
5. Matcher documentation - possibly not open if it is good enough for now.

**Comment by nreinicke** [comment]
I like the idea of open separate issues for all of these. At a minimum it would be nice to comb through each section and confirm that it looks okay (since we had a whirlwind of modifications during the sprint).

**Comment by Rowlando13** [comment]
Sounds like we should open the issues, then close them as we check.

**Comment by Rowlando13** [comment]
Opened #113 , #114 , #115 , #116 , #117 . Closing issue.
