### ISSUE TITLE
Allow the package to be installed solely by pip via PyPI

### ISSUE THREAD

**Issue by jhoshiko** [NREL/mappymatch#12]
The yamm package is ready to be installed with pip but still needs to uploaded to PyPI. Once yamm is added to PyPI, users will be able install yamm solely by pip.

**Comment by jsexauer** [comment]
You should check the `install_requires` in setup.py.  You are only listing osmnx and pygeos, but the environment.yaml also lists folium and requests and requirements.

**Comment by machallboyd** [comment]
I think I'm blocked by this so let me know if it needs another set of eyes.

**Comment by jsexauer** [comment]
FYI yamm is already on pypi: https://pypi.org/project/yamm/

Perhaps this is why #50 was created?

**Comment by jhoshiko** [comment]
Closing this issue now that the package has been renamed.
