### ISSUE TITLE
Add/update type hints

### ISSUE THREAD

**Issue by jhoshiko** [NREL/mappymatch#13]
For all new code and existing code, we should ensure that type hints are used. Arguments, return values, and instance variables should all include type hints. Below are some examples: 
 
```python 
class Trace:
    # Instance variable type hints:
    _frame: GeoDataFrame

    coords: List[Coordinate]
    crs: CRS

    # method with both argument type hints and a return type type hint
    @classmethod
    def build(cls, frame: GeoDataFrame, xy: bool = True) -> Trace:
        if xy:
            frame = frame.to_crs(XY_CRS)
        return Trace(frame)
```

**Comment by jhoshiko** [comment]
The python package mypy is a static type checker we can use to ensure that the type hints we have added are correct. We should fix any typing issues we find with mypy.

**Comment by LauraBeisser** [comment]
Mypy errors that were showing in the constructs, maps, matchers, and utils directory were resolved.  The errors regarding imported packages that don't support Mypy were not resolved. Eventually I _think_ that you could generate stub files for the packages to resolve the errors.

**Comment by nreinicke** [comment]
mypy CI checks are now passing for python 3.8-10
