### ISSUE TITLE
Update docs to explain things around pip requirements

### ISSUE THREAD

**Issue by machallboyd** [NREL/mappymatch#144]
Following PR https://github.com/NREL/mappymatch/pull/140, we've got requirements defined suitable for installation with pip, including one set for contributor installs.

 - Explain pip contributor install for non-conda contributors.
 - Explain how to add new requirements if contributing. (Add to `setup.py`)
 - Explain how to use the `pip-compile` command from [pip-tools](https://github.com/jazzband/pip-tools) to automatically generate new  pinned requirements. (Covers generating from `setup.py` for main requirements and from `requirements.in` files for other requirement sets)

**Comment by nreinicke** [comment]
For the time being, I've rolled backed our pinned requirements to keep things a bit simpler and I've added a new section into the contributor docs for how to add a new dependency (basically just add to the pyproject.toml file).
