### ISSUE TITLE
Add support for python 3.9 / 3.10

### ISSUE THREAD

**Issue by nreinicke** [NREL/mappymatch#17]
Most of the development for this package has been done with python 3.8. Investigate what it would take to support python 3.9 and python 3.10.

**Comment by machallboyd** [comment]
Planning to just start some conda environments with different versions and see if anything breaks.

**Comment by machallboyd** [comment]
Don't think it's worth working on this much until https://github.com/NREL/yamm/issues/18 and the general packaging issues are resolved.

**Comment by Rowlando13** [comment]
Going to try to get CI working and see how long it takes to build from source and run the tests.

**Comment by Rowlando13** [comment]
@nreinicke Still working on this. The docker builds and integrating with GitHub actions is proving to be very challenging. If we don't use docker and a two stage build, I think the CI tests will take 90 minutes for all the versions. I hoping that using docker and some other tricks, that I can get it down to 15 minutes. Will update you as I keep trying.

**Comment by nreinicke** [comment]
That sounds good, thanks for working through this. Do you have a sense for what is taking so long to run? Is it getting hung up on a certain package install?

**Comment by Rowlando13** [comment]
1. The conda resolver takes a long time to resolve. 
2. The image is large ~3 gigs
