### ISSUE TITLE
Might need another release (0.4.2)!

### ISSUE THREAD

**Issue by amin-sajadi** [NREL/mappymatch#180]
Hi,

After installing the package using pip or poetry, we realize that for instance in the match_result.py file, the path_to_dataframe() function is not available in the latest release 0.4.1. 

It would be very practical to have another release for this package to be installable easily with package managers like pip or poetry (to include the latest commit). 

Thank you very much for your kind support and consideration. Keep up the excellent work.

Best regards,
Amin Sajadi

**Comment by nreinicke** [comment]
Amin - Thanks for bringing this to our attention and apologies for the oversight in not releasing those minor changes! I just pushed a new release 0.4.2 that should include all of those changes. Let us know if you have any trouble with it.

**Comment by nreinicke** [comment]
Closing this since we released 0.4.2.
