### ISSUE TITLE
Examples plotting isn't Jupyter NB friendly

### ISSUE THREAD

**Issue by jakeholden** [NREL/mappymatch#3]
Testing the `match_one_trace.py` example on a remote linux server (NREL HPC), the plots do not seem to render in a Jupyter notebook.

**Comment by Econundrums** [comment]
I just tested it out on my Windows machine, and it appears that you don't need to utilize the HTML function. All you need to do is simply run the `mmap` and/or `tmap` variables in the examples, or similarly just do `plot_matches(matches = your_matches, road_map = your_roadmap)`, and Jupyter should show the map within the notebook. Perhaps it's just an issue with the remote linux server?
