### ISSUE TITLE
Load Trace from gpx file

### ISSUE THREAD

**Issue by nreinicke** [NREL/mappymatch#4]
Add a new `@classmethod` to the `Trace` class that can load a trace from a provided [GPX](https://docs.fileformat.com/gis/gpx/) file.

This could probably be done with some regex parsing, similar to [here](https://stackoverflow.com/a/65458843).

It would be nice to test this using a small sample / dummy .gpx file.

**Comment by nowheremanx** [comment]
maybe this library can solve the problem easily. It is pure python and zero dependency. Only requirement is python>=3.6

Another concern is license, can you please look into it?

**Comment by nreinicke** [comment]
Included with #45
