### ISSUE TITLE
"add_to_map" method for constructs classes

### ISSUE THREAD

**Issue by nowheremanx** [NREL/mappymatch#46]
Current plot utils do not support layer overlapping. We may want to implement a method called "add_to_map" which accepts a folium map object and additional arguments for styling...

or we can create a method to return an object (maybe a geojson layer) which can be accepted by folium.

I propose to use GeoJSON as the data format internally.

**Comment by nreinicke** [comment]
The plot functions now accept an optional parameter m for layer overlapping. For example to plot a trace and a geofence together you can do:

```python
plot_trace(trace, m=plot_geofence(geofence))
```
