### ISSUE TITLE
Determine which version of pygeos work across platforms

### ISSUE THREAD

**Issue by nreinicke** [NREL/mappymatch#47]
Determine which version of pygeos work across platforms

**Comment by jt-eic** [comment]
(Windows 10, python version 3.9.7) running in virtual environment and pip installing a pre-complied wheel for GDAL and Fiona specific to my system, I ran into a version conflict for pygeos. Default pip install brings version 0.12. I was able to manually install version 0.10.2 via pip install pygeos==0.10.2. Beyond that, it required another missing package. pip install folium. This installs version 0.12.1.post1 by default. Once completing these steps, the example files would run properly.

**Comment by LiamMeron** [comment]
Downgrading pygeos from 0.12.0 to 0.10.2 allows pygeos to match the vendored Shapely pygeos version

**Comment by nreinicke** [comment]
We're considering removing the direct pygeos dependency (see #71)

**Comment by LiamMeron** [comment]
This is closed by #71
