### ISSUE TITLE
add jupyter notebooks as a part of documentation

### ISSUE THREAD

**Issue by nowheremanx** [NREL/mappymatch#49]
We can integrate jupyter notebooks into our documentation.

Reasons:
1. add a layer of testing for notebooks
2. nice for jupyter notebook users

https://jupyterbook.org/en/stable/start/build.html

**Comment by machallboyd** [comment]
As a note, I have this open for review: https://github.com/NREL/yamm/pull/30

**Comment by nreinicke** [comment]
I really like the idea. We've started a new repository: https://github.com/NREL/mappymatch-examples to house jupyter notebooks and other examples. It could be a nice to eventually use something like jupyter-book within that repository.
