### ISSUE TITLE
Add origin and destination road ids to Road

### ISSUE THREAD

**Issue by jhoshiko** [NREL/mappymatch#60]
Currently, origin node id and destination node id are found in the [`Road.metadata`](https://github.com/NREL/yamm/blob/ef129c91a36a649a1c9660ef8101b6c0a001a6b8/yamm/constructs/road.py#L8). We should add an origin_id and dest_id attribute to `Road` and remove these ids from the metadata.

**Comment by LiamMeron** [comment]
This change is completed and a PR has been created
