### ISSUE TITLE
Figure out read the docs versioning

### ISSUE THREAD

**Issue by nreinicke** [NREL/mappymatch#69]
Read the docs supports versioning (right now we don't have multiple versions so this doesn't matter yet). We'll need to figure out how to configure read the docs to maintain a different set of documents for each version.

**Comment by Rowlando13** [comment]
Going to expand this to: 
-Add versioning to our documentation 
-Add versioning to read the docs 
-Add support to change version in all required places with single command line command 

This is to prepare for regular releases on pip and conda.
