### ISSUE TITLE
Match expects the distance attribute to be a float

### ISSUE THREAD

**Issue by sjirwin** [NREL/mappymatch#89]
`Match()` defines its `distance` attribute as `float` and code elsewhere assumes that it is a `float`.
e.g., from `compute_cutting_points()`
```
if abs(m.distance - distance_epsilon) < cutting_thresh:
                        cutting_points.append(CuttingPoint(i))
```
however, in `orsm'.py` the function `_parse_leg()` (inner function of `parse_osrm_json()`) constructs `Match` objects with `distance=None`. this is both a `mypy` error and can cause an error in functions like `compute_cutting_points()`

discussed with @nreinicke and decided to change the `None` to `float('infinity')`

**Comment by nreinicke** [comment]
Included with #90
